# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.hostname = "gitlab.gamehouse.com"
	config.vm.network :private_network, ip: "192.168.33.8"
	config.vm.provision :shell, :path => "bootstrap.sh"
  
	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end
end

